#!/bin/bash

#Runs the program in $2 and move $3 to the input of $2. Saves the output in $1, and compere $1 with $4.

"$2" < "$3" > "$1"
diff "$1" "$4" > differnce

if [[ -s differnce ]]; then
	echo "InOut X"
	exit 1
fi
echo "InOut V"
exit 0


